language: node_js
node_js:
  - '9'

dist: trusty
sudo: required

branches:
  only:
  - master
  - development

addons:
  chrome: stable
  firefox: latest

before_install:
  - pip install --user codecov

before_script:
  - npm install -g @angular/cli

script:
  - npm run lint
  - npm run test-ci
  - npm run build
  - npm run compodoc -- --disableCoverage
after_success:
  - codecov
deploy:
  skip_cleanup: true
  # Lib Release
  provider: script
  script:
    - npx semantic-release
  on:
    branch: master
  # Demo and Docs Release
  provider: script
  script:
    - npm run publish:demo
  on:
    branch: master
