language: node_js
node_js:
  - '9'

dist: trusty
sudo: required

branches:
  only:
  - master
  - development

addons:
  chrome: stable
  firefox: latest

before_install:
  - pip install --user codecov

jobs:
  include:
    - stage: build
      script:
        - npm run lint
        - npm run test-ci
        - npm run build
      before_script:
        - npm install -g @angular/cli
      after_success:
        - codecov
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: master
