language: node_js
node_js:
  - '10'

dist: trusty
sudo: required

branches:
  only:
  - master
  - development

addons:
  chrome: stable
  firefox: latest

before_install:
  - pip install --user codecov

before_script:
  - npm install -g @angular/cli
  - npm install -g copyfiles

script:
  - npm run lint
  - npm run test-ci
  - npm run package
  - npm run compodoc -- --disableCoverage
after_success:
  - codecov
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
